plugins {
    id 'java'
}

group = 'com.design'
version = '1.0-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
}

ext {
    set('lombok', "1.18.42")
}

subprojects {

    apply plugin: 'java'

    group = rootProject.group
    version = rootProject.version

    repositories {
        mavenCentral()
    }

    dependencies {
        compileOnly "org.projectlombok:lombok:${lombok}"
        annotationProcessor "org.projectlombok:lombok:${lombok}"
    }

    tasks.withType(Test).configureEach {
        useJUnitPlatform()
    }
}
